Yarmov/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from Yarmov import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    # path('market/', include(('market.urls', 'cart'), namespace='market')),
    path('market/', include('market.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('detail', cart_detail, name='cart_detail'),
    path('add/<int:pk>', cart_add, name='cart_add'),
    path('remove/<int:pk>', cart_remove, name='cart_remove'),
]

market/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('products/', ProductList.as_view(), name='products'),
    path('category/<int:pk>', ProductsOfCategory.as_view(), name='products_of_category'),
    # path('product/<int:pk>', ProductDetail.as_view(), name='product_detail'),
    path('product/<int:pk>', product_detail, name='product_detail'),
    path('order_create/', order_create, name='order_create'),
    # path('logout/', LogoutView.as_view(template_name='market/logout.html'), name='log_out'),
    path('logout/', logout_view, name='logout'),
    path('cabinet/', CabinetView.as_view(), name='cabinet'),
    path('data_create/', DataCreate.as_view(), name='data_create'),
    path('comment/<int:pk>', comment_add, name='comment_add'),

    path('about/', AboutView.as_view(), name='about'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('main/', MainView.as_view(), name='main'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('contacts/', ContactView.as_view(), name='contacts')

]

market/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


# Create your models here.
class Category (models.Model):
    name = models.CharField(max_length=50)


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    rate = models.IntegerField(default=0)
    count = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    photo = models.ImageField(blank=True, null=True)

    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    def update_rate(self):
        for c in Comments.objects.filter(product=self):
            self.rate += c.rate
        self.rate /= len(Comments.objects.filter(product=self))
        # self.rate = (Comments.objects.filter(product=self).aggregate(Sum, 'rate')).get('rate__sum')
        self.save()


class Comments(models.Model):
    comment = models.TextField()
    rate = models.IntegerField(default=1)

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='comments')



class Data(models.Model):
    address = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)

    user = models.OneToOneField(User, on_delete=models.PROTECT)


class Delivery(models.Model):
    finished = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    quantity = models.PositiveIntegerField(default=1)

    data = models.ForeignKey(Data, on_delete=models.PROTECT)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)

market/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group
from django import forms
from .models import Product, Data, Comments


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        return user


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [
            'name'
        ]


class DataCreateForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = [
            'address',
            'phone'
        ]


RATE_CHOICES = [(i, str(i)) for i in range(1, 6)]


class CommentsCreateForm(forms.Form):
    rate = forms.TypedChoiceField(choices=RATE_CHOICES, coerce=int)
    comment = forms.CharField(max_length=50)

market/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.views.generic import ListView, UpdateView, CreateView, TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .models import *
from .forms import ProductForm, DataCreateForm, CommentsCreateForm

from cart.forms import CartAddProductForm
from cart.cart import Cart


# вывод товаров
class ProductList(ListView):
    model = Product
    template_name = 'market/catalog.html'
    context_object_name = 'products'

    # достаем категории
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


# товары по определенной категории
class ProductsOfCategory(ListView):
    model = Product
    template_name = 'market/products_of_category.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return Product.objects.filter(category=self.kwargs['pk'])


# просмотр товара
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    cart_product_form = CartAddProductForm()
    return render(request, 'market/product.html', {'product': product,
                                                   'cart_product_form': cart_product_form})


# Создание данных пользователя
class DataCreate(LoginRequiredMixin, CreateView):
    model = Data
    form_class = DataCreateForm
    template_name = 'market/data_create.html'
    success_url = reverse_lazy('cabinet')

    #  добавление юзера
    def form_valid(self, form):
        cd = form.save(commit=False)
        cd.user = self.request.user
        return super().form_valid(form)


# изменение данных пользователя
class DataUpdate(LoginRequiredMixin, UpdateView):
    model = Data
    form_class = DataCreateForm
    template_name = 'market/data_create.html'
    success_url = reverse_lazy('cabinet')

    #  добавление юзера
    def form_valid(self, form):
        cd = form.save(commit=False)
        cd.user = self.request.user
        return super().form_valid(form)


# кабинет
class CabinetView(LoginRequiredMixin, TemplateView):
    template_name = 'market/cabinet.html'


class AboutView(TemplateView):
    template_name = 'market/aboutus.html'


class ContactView(TemplateView):
    template_name = 'contacts.html'


class CatalogView(TemplateView):
    template_name = 'market/catalog.html'


class CheckoutView(TemplateView):
    template_name = 'checkout.html'


class MainView(TemplateView):
    template_name = 'index.html'


# создания заказа
@login_required
def order_create(request):
    cart = Cart(request)
    data = Data.objects.get(user=request.user)
    if data:
        for item in cart:
            Delivery.objects.create(data=Data.objects.get(user=request.user),
                                    product=item['product'],
                                    price=item['price'],
                                    quantity=item['quantity'])
        # очистка корзины
        cart.clear()
        return render(request, 'market/order_created.html')
    else:
        return redirect('data_create')


# выход
@login_required
def logout_view(request):
    logout(request)
    return render(request, 'market/logout.html')


# создание комментария
def comment_add(request, pk):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=pk)
        form = CommentsCreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            c = Comments.objects.create(
                user=request.user,
                product=product,
                comment=cd['comment'],
                rate=cd['rate']
            )
            c.save()
            Product.objects.get(pk=pk).update_rate()
            return HttpResponse(render(request, 'market/comment_created.html'))
    else:
        form = CommentsCreateForm()
        return render(request, 'market/comment_create.html', context={'form': form})


# class CommentCreate(LoginRequiredMixin, CreateView):
#     model = Comments
#     form_class = CommentsCreateForm
#     template_name = 'market/comment_create.html'
#     success_url = reverse_lazy('cabinet')
#
#     def post(self, request, *args, **kwargs):
#         pk = self.kwargs['pk']
#         print(111111, pk)
#         print(2222222, request)
#         print(3333333, args)
#
#     #  добавление юзера
#     def form_valid(self, form):
#         cd = form.save(commit=False)
#         cd.user = self.request.user
#         cd.product = self.request
#         return super().form_valid(form)

templates/market/aboutus.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset= "UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BLESS&WORSHIP</title>
        {% load static %}
       <link href="{% static 'css/about_style.css' %}" rel="stylesheet" />
        <link rel="icon" href="/static/img/Vector1.svg" type="image/x-icon">
</head>
<body>
    <header style="height: 413px" class="">
        <div class="header-cont">
            <div class="menu-btn-cont">
                <div id="menu-btn" class="menu-btn"><div><div class="bars"></div></div></div>
            </div>
            <div class="site-name">BLESS</br>&WORSHIP</div>
            <div class="menu-area" style="height: 73px">
                <ul id="menu-main-menu" class="main-menu-top">
                    <li><a href="/market/main">ГЛАВНАЯ</a></li>
                    <li><a href="/market/catalog">КАТАЛОГ</a></li>
                    <li><a href="/market/checkout">КОРЗИНА</a></li>
                    <!-- <li><a href="fav.html">ИЗБРАННОЕ</a></li> -->
                    <li><a href="/market/about">О НАС</a></li>
                    <li><a href="/market/contacts">КОНТАКТЫ</a></li>
                    <div class="log">
                        <a href="/accounts/login/">Войти</a>
                    </div>
                </ul>
            </div>
        </div>
    </header>
    <main>
        <div>
            <div class="main-grad">
                <div class="grad">
                    <div class="main-head">
                        <div>
                            <h1>Bless&Worship</h1>
                            <h2>Одежда и обувь специально для тебя</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="main">
                <div class="main-sales">
                    <h3>О НАС</h3>
                    <div id="aboutus" class="main-about">
                        <p>Мы проанализировали отзывы на конкурентов и учли их ошибки и удачные решения в своей системе. 
                            Главная причина проекта – это отсутствие возможности удобного поиска необходимых товаров по фото. 
                            Мы же создали сайт, позволяющий покупателю подобрать для себя максимально похожий элемент одежды по запросу. 
                            Реализация решения проблемы достигнута благодаря использованию нейросетей. 
                            Наша информационная система умеет классифицировать товар по фото, что значительно упрощает поиск новых элементов Вашего гардероба.</p>
                    </div>
                    <div class="hh">
                        <h4>Bless&Worship - это про стиль и качество</h4>
                        <h5>Очаровывай вместе с нами</h5>
                    </div>
                    <div>
                        <h6>Почему мы</h6>
                        <div class="points">
                            <p>Безопасность</p>
                            <p>
                                Безопасность платежей гарантируется использованием SSL протокола. 
                                Данные вашей банковской карты надежно защищены при оплате онлайн.
                            </p>
                        </div>
                        <div  class="points">
                            <p>Бесплатная доставка по всей России</p>
                            <p>У вас всегда есть возможность получить бесплатную доставку товаров.</p>
                        </div>
                        <div  class="points">
                            <p>Примерка</p>
                            <p>Примеряйте и оплачивайте только подходящие товары. Вы можете примерить вещи перед покупкой и взять лишь те, которые вам подошли.</p>
                        </div>
                    </div>

                </div>
                <div class="start"><a href="catalog.html"><img src="./img/Начатьпокупки.svg" alt=""></a></div>
                
            </div>
        </div>
    </main>
    <footer>
        <div class="footer">
            <div class="footer-left">
                <img src="./img/Полоскафутера.svg" alt="">
                <h4>2023<br>© Bless&Worship</h4>
                <p>Все права защищены</p>
                <p style="max-width: 200px;">Копирование и использование данных с сайта без разрешения правообладателей запрещены</p>
            </div>
            <div class="socials">
                <div class="social telegram">
                    <a href="https://t.me/darinastepanova" target="_blank">
                        <svg role="img" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M446.7 98.6l-67.6 318.8c-5.1 22.5-18.4 28.1-37.3 17.5l-103-75.9-49.7 47.8c-5.5 5.5-10.1 10.1-20.7 10.1l7.4-104.9 190.9-172.5c8.3-7.4-1.8-11.5-12.9-4.1L117.8 284 16.2 252.2c-22.1-6.9-22.5-22.1 4.6-32.7L418.2 66.4c18.4-6.9 34.5 4.1 28.5 32.2z"/>
                        </svg>
                    </a>
                </div>
                <div class="social vk">
                    <a href="https://vk.com/darishka_stepanova" target="_blank">
                        <svg role="img" viewBox="0 0 576 512">
                            <path fill="currentColor" d="M545 117.7c3.7-12.5 0-21.7-17.8-21.7h-58.9c-15 0-21.9 7.9-25.6 16.7 0 0-30 73.1-72.4 120.5-13.7 13.7-20 18.1-27.5 18.1-3.7 0-9.4-4.4-9.4-16.9V117.7c0-15-4.2-21.7-16.6-21.7h-92.6c-9.4 0-15 7-15 13.5 0 14.2 21.2 17.5 23.4 57.5v86.8c0 19-3.4 22.5-10.9 22.5-20 0-68.6-73.4-97.4-157.4-5.8-16.3-11.5-22.9-26.6-22.9H38.8c-16.8 0-20.2 7.9-20.2 16.7 0 15.6 20 93.1 93.1 195.5C160.4 378.1 229 416 291.4 416c37.5 0 42.1-8.4 42.1-22.9 0-66.8-3.4-73.1 15.4-73.1 8.7 0 23.7 4.4 58.7 38.1 40 40 46.6 57.9 69 57.9h58.9c16.8 0 25.3-8.4 20.4-25-11.2-34.9-86.9-106.7-90.3-111.5-8.7-11.2-6.2-16.2 0-26.2.1-.1 72-101.3 79.4-135.6z"/>
                        </svg>
                    </a>
                </div>
                <div class="social instagram">
                    <a href="https://instagram.com/darina_stepanova" target="_blank">
                        <svg role="img" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/>
                        </svg>
                    </a>
                </div>
            </div> 
            <img src="/static/img/VectorFoot.svg" alt="">
        </div>
    </footer>
<script type="text/javascript" src="/static/css/jquery.js"></script>
<script type="text/javascript" src="/static/css/slick.min.js"></script>
<script type="text/javascript" src="/static/css/main.js"></script>
</body>
</html>

templates/market/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
</head>
<body>
<div id="header">
    <a href="/" class="logo">My shop</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} item{{ total_items|pluralize }},
                    ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/market/cabinet.html
{% extends "market/base.html" %}
{% block content %}
<h2> Добро пожаловать, {{request.user.username}} </h2>
{% endblock %}

templates/market/catalog.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset= "UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BLESS&WORSHIP</title>
        <link rel="stylesheet" href="/static/css/cat_style.css">
        <link rel="icon" href="/static/img/Vector1.svg" type="image/x-icon">
</head>
<body>
    <header style="height: 413px" class="">
        <div class="header-cont">
            <div class="menu-btn-cont">
                <div id="menu-btn" class="menu-btn"><div><div class="bars"></div></div></div>
            </div>
            <div class="site-name">BLESS</br>&WORSHIP</div>
            <div class="menu-area" style="height: 73px">
                <ul id="menu-main-menu" class="main-menu-top">
                    <li><a href="/market/main">ГЛАВНАЯ</a></li>
                    <li><a href="/market/catalog">КАТАЛОГ</a></li>
                    <li><a href="/market/checkout">КОРЗИНА</a></li>
                    <!-- <li><a href="fav.html">ИЗБРАННОЕ</a></li> -->
                    <li><a href="/market/about">О НАС</a></li>
                    <li><a href="/market/contacts">КОНТАКТЫ</a></li>
                    <div class="log">
                        <a href="/accounts/login/">Войти</a>
                    </div>
                </ul>
            </div>
        </div>
    </header>
    <main>
        <div>
            <div class="main">
                <div class="main-cat">
                    <div class="main-cat-head">
                        <h3>Каталог</h3>
                        <a href=""><img src="/static/img/autofilt.svg" alt=""></a>
                    </div>
                    <!-- <div class="sales">
                        <div class="elems">
                            <a href=" " class="tit">Одежда</a>
                            <ul>
                                <li><a href=" ">Блузы и рубашки</a></li>
                                <li><a href=" ">Брюки</a></li>
                                <li><a href=" ">Верхняя одежда</a></li>
                                <li><a href=" ">Платья и сарафаны</a></li>
                                <li><a href=" ">Джемперы, свитеры и кадиганы</a></li>
                                <li><a href=" ">Пиджаки и костюмы</a></li>
                                <li><a href=" ">Юбки и шорты</a></li>
                            </ul>
                        </div>
                        <div class="elems">
                            <a href=" " class="tit">Обувь</a>
                            <ul>
                                <li><a href=" ">Балетки</a></li>
                                <li><a href=" ">Босоножки</a></li>
                                <li><a href=" ">Ботинки</a></li>
                                <li><a href=" ">Спортивная обувь</a></li>
                                <li><a href=" ">Сапоги</a></li>
                                <li><a href=" ">Туфли</a></li>
                            </ul>
                        </div>
                        <div class="elems">
                            <a href=" "  class="tit">Аксессуары</a>
                            <ul>
                                <li><a href=" ">Сумки и рюкзаки</a></li>
                                <li><a href=" ">Очки</a></li>
                                <li><a href=" ">Платки и шарфы</a></li>
                                <li><a href=" ">Головные уборы</a></li>
                            </ul>
                        </div>
                    </div> -->
                    <div class="wrapper">
                        <div id="search-container">
                          <input
                            type="search"
                            id="search-input"
                            placeholder="Введите название..."
                          />
                          <button id="search">Найти</button>
                        </div>
                        <div id="buttons">
                          <button class="button-value" onclick="filterProduct('Все')">Все</button>
                          <button class="button-value" onclick="filterProduct('Верхняяодежда')">
                            Верхняя одежда
                          </button>
                          <button class="button-value" onclick="filterProduct('Блузыирубашки')">
                            Блузы и рубашки
                          </button>
                          <button class="button-value" onclick="filterProduct('Пиджакиикостюмы')">
                            Пиджаки и костюмы
                          </button>
                          <button class="button-value" onclick="filterProduct('Платья')">
                            Платья
                          </button>
                        </div>
                        <div id="products"></div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="footer">
            <div class="footer-left">
                <img src="/static/img/Полоскафутера.svg" alt="">
                <h4>2023<br>© Bless&Worship</h4>
                <p>Все права защищены</p>
                <p style="max-width: 200px;">Копирование и использование данных с сайта без разрешения правообладателей запрещены</p>
            </div>
            <div class="socials">
                <div class="social telegram">
                    <a href="https://t.me/darinastepanova" target="_blank">
                        <svg role="img" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M446.7 98.6l-67.6 318.8c-5.1 22.5-18.4 28.1-37.3 17.5l-103-75.9-49.7 47.8c-5.5 5.5-10.1 10.1-20.7 10.1l7.4-104.9 190.9-172.5c8.3-7.4-1.8-11.5-12.9-4.1L117.8 284 16.2 252.2c-22.1-6.9-22.5-22.1 4.6-32.7L418.2 66.4c18.4-6.9 34.5 4.1 28.5 32.2z"/>
                        </svg>
                    </a>
                </div>
                <div class="social vk">
                    <a href="https://vk.com/darishka_stepanova" target="_blank">
                        <svg role="img" viewBox="0 0 576 512">
                            <path fill="currentColor" d="M545 117.7c3.7-12.5 0-21.7-17.8-21.7h-58.9c-15 0-21.9 7.9-25.6 16.7 0 0-30 73.1-72.4 120.5-13.7 13.7-20 18.1-27.5 18.1-3.7 0-9.4-4.4-9.4-16.9V117.7c0-15-4.2-21.7-16.6-21.7h-92.6c-9.4 0-15 7-15 13.5 0 14.2 21.2 17.5 23.4 57.5v86.8c0 19-3.4 22.5-10.9 22.5-20 0-68.6-73.4-97.4-157.4-5.8-16.3-11.5-22.9-26.6-22.9H38.8c-16.8 0-20.2 7.9-20.2 16.7 0 15.6 20 93.1 93.1 195.5C160.4 378.1 229 416 291.4 416c37.5 0 42.1-8.4 42.1-22.9 0-66.8-3.4-73.1 15.4-73.1 8.7 0 23.7 4.4 58.7 38.1 40 40 46.6 57.9 69 57.9h58.9c16.8 0 25.3-8.4 20.4-25-11.2-34.9-86.9-106.7-90.3-111.5-8.7-11.2-6.2-16.2 0-26.2.1-.1 72-101.3 79.4-135.6z"/>
                        </svg>
                    </a>
                </div>
                <div class="social instagram">
                    <a href="https://instagram.com/darina_stepanova" target="_blank">
                        <svg role="img" viewBox="0 0 448 512">
                            <path fill="currentColor" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/>
                        </svg>
                    </a>
                </div>
            </div>
            <img src="/static/img/VectorFoot.svg" alt="">
        </div>
    </footer>
<script type="text/javascript" src="/static/css/jquery.js"></script>
<script type="text/javascript" src="/static/css/slick.min.js"></script>
<script type="text/javascript" src="/static/css/main.js"></script>
<!-- Script -->
<script type="text/javascript"  src="/static/css/script.js"></script>
</body>
</html>

templates/market/comment_create.html
{% block content %}
    <h1>Registration</h1>
    <hr>
    <form method="post">
      {% csrf_token %}
        {{form}}
        <button type="submit">Send</button>
    </form>
{% endblock content %}

templates/market/comment_created.html
{% extends "market/base.html" %}
{% block content %}
<h2>{{request.user.username}}, отзыв оставлен</h2>
{% endblock %}

templates/market/data_create.html
{% block title %}
    Ваши данные
{% endblock title %}

{% block content %}
   <form method="post">
       {% csrf_token %}
       {{ form.media }}
       {{form.as_p}}
       <input type="submit" value="Применить">
   </form>
{% endblock content %}

templates/market/logout.html
{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

templates/market/order_created.html
{% extends "market/base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

templates/market/product.html
{% extends 'market/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        <form action="{% url 'cart:cart_add' product.pk %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        <img src="{% if product.photo %}{{ product.photo.url }}{% endif %}">
    </div>


{% endblock %}